### ISSUE TITLE
uhhhh... Help?

### ISSUE THREAD

**Issue by Arleeb** [MyrikLD/LinusTrinus#11]
When i try to open main.py, i got this error

`
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from frame_generator import FrameGenerator
  File "/home/arleeb/Desktop/LinusTrinus-master/frame_generator.py", line 29
    return f"{self.width}x{self.height}"
                                       ^
SyntaxError: invalid syntax
`

**Comment by MyrikLD** [comment]
Solved, check
