### ISSUE TITLE
não open ubuntu 

### ISSUE THREAD

**Issue by lordars** [MyrikLD/LinusTrinus#34]
Traceback (most recent call last):
  File "/home/lordars/Downloads/LinusTrinus/main.py", line 8, in <module>
    from frame_generator.xwd_fg import XwdFrameGenerator
  File "/home/lordars/Downloads/LinusTrinus/frame_generator/xwd_fg.py", line 6, in <module>
    from wand.image import Image
ModuleNotFoundError: No module named 'wand'

**Comment by FluffHound** [comment]
Install Wand
sudo apt-get install python-wand

**Comment by lordars** [comment]
yes, itś work but  the image not found. i am close the threade. thanks.
